name: guidance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.5
  pdf: ^3.11.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
